name: build on Windows 2022
on:
  workflow_dispatch:
  push:
    tags:
      - v*
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  QT_VERSION: "6.9.1"
  MINGW_VERSION: "win64_mingw"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022, windows-2025 ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install zlib with vcpkg
        shell: pwsh
        run: |
          vcpkg install zlib #tbb
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'windows'
          target: 'desktop'
          arch: ${{ env.MINGW_VERSION }}
          install-deps: 'true'
          modules: 'qt5compat qthttpserver'
          setup-python: 'false'
          set-env: 'true'
          tools: 'tools_mingw1310' # base 12.2 with link error
      - name: Configure FreeLib
        run: cmake -DCMAKE_PREFIX_PATH=C:/mingw64/ -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles" -B ${{github.workspace}}/freeLib-${{ matrix.os }}-build
      - name: Build FreeLib
        run: cmake --build ${{github.workspace}}\freeLib-${{ matrix.os }}-build --config ${{env.BUILD_TYPE}} -j4
      - name: Install FreeLib
        run: cmake --install ${{github.workspace}}\freeLib-${{ matrix.os }}-build --prefix ${{github.workspace}}\freeLib-${{ matrix.os }}-final
      - name: Compress portable program
        run: |
          cd ${{github.workspace}}\freeLib-${{ matrix.os }}-final\bin
          windeployqt.exe freelib.exe --release --no-translations --no-system-d3d-compiler --no-opengl-sw 
          # libzlib.dll v1.3.1 auto copy with windeployqt, but need manual install without vcpkg
          Copy-Item -Path "C:/vcpkg/installed/x64-windows/bin/zlib1.dll" -Destination .
          # Copy-Item -Path "${{github.workspace}}\freeLib-${{ matrix.os }}-final\share\freelib\translations\*" -Destination translations
      - name: always
        uses: actions/upload-artifact@v4
        with:
          name: freeLib-${{ matrix.os }}
          path: ${{github.workspace}}/freeLib-${{ matrix.os }}-final/bin/
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: freeLib-*
          body: "Automated release from the release tag."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
