name: build on Windows 2022
on:
  workflow_dispatch:
  push:
    tags:
      - Release.*
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  QT_VERSION: "6.9.1"
  MINGW_VERSION: "win64_mingw"

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install zlib with vcpkg
        shell: pwsh
        run: |
          vcpkg install zlib #tbb
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'windows'
          target: 'desktop'
          arch: ${{ env.MINGW_VERSION }}
          install-deps: 'true'
          modules: 'qt5compat qthttpserver'
          setup-python: 'false'
          set-env: 'true'
          tools: 'tools_mingw1310' # base 12.2 with link error
      - name: Configure FreeLib
        run: cmake -DCMAKE_PREFIX_PATH=C:/mingw64/ -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles" -B ${{github.workspace}}/build
      - name: Build FreeLib
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}} -j4
      - name: Install FreeLib
        run: cmake --install ${{github.workspace}}\build --prefix ${{github.workspace}}\final
      - name: Compress portable program
        run: |
          cd ${{github.workspace}}\final\bin
          windeployqt.exe freelib.exe --release --no-translations --no-system-d3d-compiler --no-opengl-sw 
          Copy-Item -Path "C:/vcpkg/installed/x64-windows/bin/zlib1.dll" -Destination .
          Copy-Item -Path "${{github.workspace}}\final\share\translations\*" -Destination translations
      - name: always
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: ${{github.workspace}}/final/bin/
